Task 4
qsqnk/formal-lang-course pull request #4
Opened 2022-10-02 20:40 UTC by qsqnk

# Задача 4. Регулярные запросы для нескольких стартовых вершин

* **Мягкий дедлайн**: 02.10.2022, 23:59
* **Жёсткий дедлайн**: 05.10.2022, 23:59
* Полный балл: 5

## Задача

- [x] Используя [разреженные матрицы из sciPy](https://docs.scipy.org/doc/scipy/reference/sparse.html) реализовать **функцию** достижимости с регулярными ограничениями для нескольких стартовых вершин.
  - Предусмотрите два варианта задачи:
    - Для указанного множества стартовых вершин найти множество достижимых.
    - Для каждой вершины из указанного множества найти множество достижимых вершин.
- [x] На основе реализованной функции реализовать **функцию** выполнения регулярных запросов к графам. Не забыть предоставить возможность задавать стартовые и финальные вершины в графе и вариант решаемой задачи.
  - Для конструирования регулярного запроса и графа использовать результаты [Задачи 2](https://github.com/JetBrains-Research/formal-lang-course/blob/main/tasks/task2.md).
- [x] Добавить необходимые тесты.

2022-10-04 16:35 UTC, rustam-azimov requested changes

2022-10-04 16:35 UTC, rustam-azimov commented on project/matrix_utils.py
> +            Means calculates achievable for each node separately or not
reachability

2022-10-04 16:35 UTC, rustam-azimov commented on project/rpq.py
> +        where U is start node and V is node reachable from U
про final nodes забыли

2022-10-04 16:35 UTC, rustam-azimov commented on project/matrix_utils.py
> +            Means calculates achievable for each node separately or not
achievable - не то слово

2022-10-04 16:35 UTC, rustam-azimov commented on project/rpq.py
> +    return nfa_bool_mtx.sync_bfs(
Результат выполнения rpq_bfs должен быть множеством вершин графа, либо множеством пар вершин графа. В этой функции надо конвертировать ответ в вершины graph node, так как пользователь дал граф и хочет результат получить в терминах этого графа. И в rpq_tensor исправьте тоже

2022-10-04 17:26 UTC, qsqnk commented on project/rpq.py
> +    return nfa_bool_mtx.sync_bfs(
Сейчас так и сделано. В обоих случаях мы отдаем не стейты, а value стейтов. Это и есть вершины в терминах графа

2022-10-04 17:34 UTC, qsqnk commented on project/rpq.py
> +    return nfa_bool_mtx.sync_bfs(
В `rpq_tensor`:
```
state_from_graph_value, _ = state_from.value
state_to_graph_value, _ = state_to.value
result.add(
    (state_from_graph_value, state_to_graph_value),
)
```

В `sync_bfs`:
```
result.add(
    self_state.value
    if not reachable_per_node
    else (
        ordered_start_states[i // other_states_num].value,
        self_state.value,
    )
)
```

2022-10-09 11:13 UTC, rustam-azimov approved these changes

2022-10-09 11:33 UTC, merged